### ISSUE TITLE
where to find the "nucleotide_VB_vs_DutchB_wHXB2.fasta" file?

### ISSUE THREAD

**Issue by liamxg** [ChrisHIV/hiv_hypervirulent_lineage_code#1]
Dear @ChrisHIV,

Could you please tell me "nucleotide_VB_vs_DutchB_wHXB2.fasta" file, thanks.

**Comment by ChrisHIV** [comment]
See the README for this repository

**Comment by ChrisHIV** [comment]
(in the "seqs" subdirectory of that data file)

**Comment by ChrisHIV** [comment]
I've made the repository README slightly clearer
